wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/images.tar.gz.aa
wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/images.tar.gz.ab
wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/images.tar.gz.ac
wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/images.tar.gz.ad
wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/images.tar.gz.ae
wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/images.tar.gz.af
wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/images.tar.gz.ag
wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/images.tar.gz.ah
wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/images.tar.gz.ai
wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/images.tar.gz.aj
wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/images.tar.gz.ak
wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/images.tar.gz.al
wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/images.tar.gz.am
wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/images.tar.gz.an
wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/images.tar.gz.ao
wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/images.tar.gz.ap
wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/images.tar.gz.aq
wget https://huggingface.co/datasets/mint-medmax/medmax_data/resolve/main/slake.tar.gz
